"""OpenAI image generation helper (ported from the notebook)."""
import base64
import os

from openai import OpenAI

from app.config import OPENAI_IMAGE_MODEL


def _openai_generate_image_bytes(prompt: str, size: str = "1024x1024", quality: str = "low") -> bytes:
    """
    Returns raw image bytes generated by OpenAI's cheapest image model.
    Requires: pip install openai
    Env var: OPENAI_API_KEY
    """

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set.")

    client = OpenAI(api_key=api_key)

    resp = client.images.generate(
        model=OPENAI_IMAGE_MODEL,
        prompt=prompt,
        size=size,
        quality=quality,
        n=1,
    )

    image = resp.data[0]
    b64 = getattr(image, "b64_json", None)
    if not b64:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")
    return base64.b64decode(b64)
